class Admin::BaseController < ApplicationController
  layout 'admin'

  # private
  # Process AJAX request generated by jquery datatables plugin, prepare an object which contains information to be used in
  # ActiveRecord operation, result object properties TBD
  # 对于需要排序字段和json中获取数据字段不同的列，用data设置获取数据节点，用name设置排序字段名称
  # def decode_datatables_params
  #   row_start = params['start'].to_i
  #   rows_per_page = params['length'].to_i
  #   search_text = params['search']['value']
  #
  #   # Convert hashed arrays into array
  #   columns = []
  #   params['columns'].each do |k, v|
  #     v['name'] = v['data'] if v['name'].blank?
  #     columns[k.to_i] = v
  #   end
  #   order_columns = []
  #   order_expressions = []
  #   params['order'].each do |k, v|
  #     v['column'] = v['column'].to_i
  #     order_expressions << "#{columns[v['column']]['name']} #{v['dir']}"
  #     order_columns[k.to_i] = v
  #   end
  #
  #   # Now let's rock it and do the processing
  #   {
  #       per_page: rows_per_page,
  #       page: row_start/rows_per_page + 1,
  #       columns: columns,
  #       order_columns: order_columns,
  #       sort_statement: order_expressions.join(','),
  #       search_text: search_text
  #   }
  # end
end